backup_dir: ~/speedy_qc/backups
checkboxes:
- No Finding
- Enlarged Cardiomediastinum
- Cardiomegaly
- Lung Lesion (Mass/Nodule)
- Airspace Opacity
- Edema
- Consolidation
- Pneumonia
- Atelectasis / Collapse
- Pneumothorax / Pneumomediast.
- Pleural Effusion
- Pleural Other
- Fracture
- Support Devices
- Other Finding
log_dir: ~/speedy_qc/logs
max_backups: 20
backup_interval: 2
tristate_cboxes: true
