backup_dir: /Users/ianselby/speedy_qc/backups
backup_interval: 5
checkboxes:
- QC1
- QC2
- QC3
- QC4
- QC5
log_dir: /Users/ianselby/speedy_qc/logs
max_backups: 10
radiobuttons:
- labels:
  - 1
  - 2
  - 3
  - 4
  title: Radiobuttons
tristate_checkboxes: true
