backup_dir: ~/speedy_iqa/backups
backup_interval: 5
log_dir: ~/speedy_iqa/logs
max_backups: 10
radiobuttons_page1:
- labels:
  - 1
  - 2
  - 3
  - 4
  title: Overall Quality
radiobuttons_page2:
- labels:
  - 1
  - 2
  - 3
  - 4
  title: Contrast
- labels:
  - 1
  - 2
  - 3
  - 4
  title: Noise
- labels:
  - 1
  - 2
  - 3
  - 4
  title: Artefacts
task: General use
